apiVersion: v1
kind: Pod
metadata:
  name: development.db-pod-redis
  namespace: development.db
  labels:
    env: development
    local: development.db
    app: redis
spec:
  containers:
    - name: redis
      image: redis:6.2.5-alpine
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 6379